name: x_rent
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+6

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.2.1
  introduction_screen: ^4.0.0
  intl_phone_number_input: ^0.7.4
  intl: ^0.20.2
  flutter_spinkit: ^5.2.2
  dio: ^5.9.0
  provider: ^6.1.5+1
  overlay_support: ^2.1.0
  shared_preferences: ^2.5.3
  multiselect_formfield: ^0.1.7
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icons/launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icons/launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icons/launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/rentals.png

    #Icons
    - assets/images/icons/exchange.png
    - assets/images/icons/filter.png
    - assets/images/icons/home.png
    - assets/images/icons/bank.png
    - assets/images/icons/left-arrow.png
    - assets/images/icons/info.png
    - assets/images/icons/user.png
    - assets/images/avatar.jpg
    - assets/images/apartment.png
    - assets/images/icons/logo.png
   

    #Illustrations
    - assets/illustrations/tenant.png
    - assets/illustrations/transaction.png
    - assets/illustrations/invoice.png
    - assets/illustrations/organize.png
    - assets/illustrations/manage_properties.png
    - assets/illustrations/view_rentals.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
